version: '3.8'

services:
  app:
    container_name: TsExpressAuthSockets
    build: .
    ports:
      - "${PORT}:${PORT}"
      - "${WS_PORT}:${WS_PORT}"
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${TYPEORM_DB_NAME}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
